server:
  port: 8084
spring:
  activemq:
    broker-url: tcp://192.168.92.129:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true #false = queue,true=topic

myTopicName: springboot-activemq-topic