server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GG1024/springcloud2020-config.git #Github上的git仓库名字
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - springcloud2020-config
      ##读取分支
      label: master
  rabbitmq:
    host: 192.168.92.129
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka

#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
